# Generated by Django 2.2.5 on 2021-08-02 08:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('birdness', models.IntegerField()),
                ('usefulness', models.IntegerField()),
                ('enjoyability', models.IntegerField()),
                ('grade', models.CharField(max_length=3)),
                ('mean_user_score', models.FloatField()),
                ('term_taken', models.CharField(max_length=20)),
                ('date_time_created', models.DateTimeField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wlugoapp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('program', models.CharField(max_length=20)),
                ('graduating_year', models.IntegerField()),
                ('has_access', models.BooleanField()),
                ('is_mod', models.BooleanField()),
                ('is_admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('date_time_created', models.DateTimeField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wlugoapp.Course')),
                ('rating_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wlugoapp.Rating')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wlugoapp.User')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wlugoapp.User'),
        ),
        migrations.CreateModel(
            name='Professor_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wlugoapp.Course')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wlugoapp.Professor')),
            ],
        ),
    ]
