# Generated by Django 3.2.6 on 2021-08-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlugoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
