# Generated by Django 2.2.5 on 2021-07-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlugoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='birdness',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='enjoyability',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='usefulness',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduating_year',
            field=models.IntegerField(),
        ),
    ]
