# Generated by Django 2.2.5 on 2021-08-01 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wlugoapp', '0003_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
