# Generated by Django 3.2.6 on 2021-08-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlugoapp', '0003_auto_20210812_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
    ]
