# Generated by Django 3.2.6 on 2021-08-12 03:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('birdness', models.IntegerField()),
                ('usefulness', models.IntegerField()),
                ('enjoyability', models.IntegerField()),
                ('grade', models.CharField(max_length=3)),
                ('mean_user_score', models.FloatField()),
                ('term_taken', models.CharField(max_length=20)),
                ('review', models.TextField(default='')),
                ('date_time_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wlugoapp.course')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wlugoapp.professor')),
            ],
        ),
    ]
