# Generated by Django 3.2.6 on 2021-08-12 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wlugoapp', '0004_alter_rating_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='date_time_created',
        ),
    ]
