# Generated by Django 3.2.6 on 2021-08-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlugoapp', '0005_remove_rating_date_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='course_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
